apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah-build-push
spec:
  params:
    - name: IMAGE
      type: string
    - name: CONTEXT
      type: string
      default: .
    - name: DOCKERFILE
      type: string
      default: ./Dockerfile
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: registry.redhat.io/rhel8/buildah:latest
      workingDir: $(workspaces.source.path)/repo
      securityContext:
        runAsUser: 0
        privileged: true
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        buildah bud -f "$(params.DOCKERFILE)" -t "$(params.IMAGE)" "$(params.CONTEXT)"
        buildah push "$(params.IMAGE)"
