apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-test-build
spec:
  params:
    - name: PACKAGE
      type: string
      default: "./..."
    - name: CGO_ENABLED
      type: string
      default: "0"
    - name: GOOS
      type: string
      default: linux
    - name: GOARCH
      type: string
      default: amd64
    - name: OUTPUT
      type: string
      default: app
  workspaces:
    - name: source
    - name: go-cache
      optional: true
  steps:
    - name: test
      image: registry.access.redhat.com/ubi9/go-toolset:latest
      workingDir: $(workspaces.source.path)/repo
      env:
        - name: GOMODCACHE
          value: $(workspaces.go-cache.path)/pkg/mod
        - name: GOCACHE
          value: $(workspaces.go-cache.path)/build-cache
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        go test $(params.PACKAGE)

    - name: build
      image: registry.access.redhat.com/ubi9/go-toolset:latest
      workingDir: $(workspaces.source.path)/repo
      env:
        - name: CGO_ENABLED
          value: $(params.CGO_ENABLED)
        - name: GOOS
          value: $(params.GOOS)
        - name: GOARCH
          value: $(params.GOARCH)
        - name: GOMODCACHE
          value: $(workspaces.go-cache.path)/pkg/mod
        - name: GOCACHE
          value: $(workspaces.go-cache.path)/build-cache
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p dist
        go build -o dist/$(params.OUTPUT) .
